import { Alert, Report, TransportRoute, AreaSummary } from '../store';

export const MOCK_USER = {
  id: 'demo-user-001',
  phone: '+18686000000',
  display_name: 'Demo User',
  district_code: 'POS',
  verified: true,
};

export const MOCK_ALERTS: Alert[] = [
  {
    id: 'alert-001',
    type: 'flood',
    severity: 'critical',
    title: 'Flood Warning — Beetham Highway',
    body: 'Severe flooding reported along the Beetham Highway between Sea Lots and Laventille overpass. Water levels are rising rapidly. Motorists are advised to avoid the area and seek alternate routes via the Priority Bus Route.',
    source: 'ODPM',
    district_code: 'POS',
    lat: 10.6400,
    lng: -61.4900,
    radius_km: 3,
    active: true,
    created_at: new Date(Date.now() - 25 * 60000).toISOString(),
  },
  {
    id: 'alert-002',
    type: 'weather',
    severity: 'warning',
    title: 'Heavy Rain Advisory — Northern Range',
    body: 'The Trinidad and Tobago Meteorological Service has issued a heavy rain advisory for communities in the Northern Range including Maracas, Blanchisseuse and Las Cuevas. Residents should be on alert for flash flooding and landslides.',
    source: 'Met Office TT',
    district_code: 'SNG',
    lat: 10.7200,
    lng: -61.3700,
    radius_km: 20,
    active: true,
    created_at: new Date(Date.now() - 90 * 60000).toISOString(),
  },
  {
    id: 'alert-003',
    type: 'water_outage',
    severity: 'warning',
    title: 'Planned Water Interruption — Chaguanas',
    body: 'WASA advises that water supply will be interrupted in Chaguanas Central, Edinburgh 500, and Edinburgh Gardens from 10:00pm tonight until approximately 6:00am tomorrow to facilitate urgent main repairs. Residents are asked to store water in advance.',
    source: 'WASA',
    district_code: 'CHG',
    lat: 10.5168,
    lng: -61.4111,
    active: true,
    created_at: new Date(Date.now() - 3 * 3600000).toISOString(),
  },
  {
    id: 'alert-004',
    type: 'power_outage',
    severity: 'info',
    title: 'Scheduled Maintenance — Diego Martin',
    body: 'T&TEC will conduct scheduled maintenance in the Diego Martin, West Moorings and Glencoe areas on Saturday between 8:00am and 2:00pm. Power will be temporarily interrupted during this period.',
    source: 'T&TEC',
    district_code: 'DGO',
    lat: 10.7300,
    lng: -61.5650,
    active: true,
    created_at: new Date(Date.now() - 6 * 3600000).toISOString(),
  },
  {
    id: 'alert-005',
    type: 'road_closure',
    severity: 'info',
    title: 'Road Closure — Lady Young Road',
    body: 'Lady Young Road will be closed to all vehicular traffic between the Hilton Hotel junction and Morvant junction from Friday 11:00pm to Saturday 5:00am for emergency drainage works.',
    source: 'ODPM',
    district_code: 'SJU',
    lat: 10.6540,
    lng: -61.4900,
    active: true,
    created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
];

export const MOCK_REPORTS: Report[] = [
  {
    id: 'report-001',
    type: 'flooding',
    description: 'Water up to the car doors on Wrightson Road near the car park. Cannot pass.',
    status: 'open',
    upvotes: 14,
    district_code: 'POS',
    lat: 10.6465,
    lng: -61.5108,
    created_at: new Date(Date.now() - 18 * 60000).toISOString(),
  },
  {
    id: 'report-002',
    type: 'blocked_drain',
    description: 'Main drain on Cipero Street completely blocked with debris. Road flooding every time it rains.',
    status: 'acknowledged',
    upvotes: 9,
    district_code: 'SFO',
    lat: 10.2796,
    lng: -61.4683,
    created_at: new Date(Date.now() - 4 * 3600000).toISOString(),
  },
  {
    id: 'report-003',
    type: 'water_outage',
    description: 'No water since Tuesday morning. WASA not responding to calls.',
    status: 'open',
    upvotes: 22,
    district_code: 'CHG',
    lat: 10.5200,
    lng: -61.4050,
    created_at: new Date(Date.now() - 2 * 24 * 3600000).toISOString(),
  },
  {
    id: 'report-004',
    type: 'fallen_tree',
    description: 'Large immortelle tree fallen across Eastern Main Road near Arima bypass. One lane blocked.',
    status: 'in_progress',
    upvotes: 7,
    district_code: 'ARI',
    lat: 10.6362,
    lng: -61.2831,
    created_at: new Date(Date.now() - 1.5 * 3600000).toISOString(),
  },
  {
    id: 'report-005',
    type: 'burst_main',
    description: 'Burst main on Dundonald Street. Water running down the road for over 3 hours.',
    status: 'open',
    upvotes: 5,
    district_code: 'POS',
    lat: 10.6513,
    lng: -61.5042,
    created_at: new Date(Date.now() - 45 * 60000).toISOString(),
  },
];

export const MOCK_TRANSPORT: TransportRoute[] = [
  {
    id: 'route-001',
    code: 'PTSC-PBR',
    name: 'Priority Bus Route',
    type: 'ptsc',
    origin: 'City Gate, Port of Spain',
    destination: 'Arima',
    status: 'delayed',
    delay_mins: 25,
    status_note: 'Delays due to flooding on Beetham Highway. Buses diverting via Churchill-Roosevelt.',
    last_updated: new Date(Date.now() - 10 * 60000).toISOString(),
  },
  {
    id: 'route-002',
    code: 'PTSC-SFD',
    name: 'San Fernando Express',
    type: 'ptsc',
    origin: 'City Gate, Port of Spain',
    destination: 'San Fernando',
    status: 'normal',
    delay_mins: 0,
    status_note: null,
    last_updated: new Date(Date.now() - 30 * 60000).toISOString(),
  },
  {
    id: 'route-003',
    code: 'MAXI-EW',
    name: 'East-West Corridor',
    type: 'maxi_taxi',
    origin: 'City Gate, Port of Spain',
    destination: 'Arima',
    status: 'delayed',
    delay_mins: 15,
    status_note: 'Heavy traffic on Eastern Main Road.',
    last_updated: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    id: 'route-004',
    code: 'MAXI-NS',
    name: 'North-South Corridor',
    type: 'maxi_taxi',
    origin: 'City Gate, Port of Spain',
    destination: 'San Fernando',
    status: 'normal',
    delay_mins: 0,
    status_note: null,
    last_updated: new Date(Date.now() - 20 * 60000).toISOString(),
  },
  {
    id: 'route-005',
    code: 'MAXI-CHG',
    name: 'Chaguanas Express',
    type: 'maxi_taxi',
    origin: 'City Gate, Port of Spain',
    destination: 'Chaguanas',
    status: 'cancelled',
    delay_mins: 0,
    status_note: 'Service suspended. Flooding on Uriah Butler Highway.',
    last_updated: new Date(Date.now() - 8 * 60000).toISOString(),
  },
  {
    id: 'route-006',
    code: 'WATER-POS-TOB',
    name: 'Port of Spain — Scarborough',
    type: 'water_taxi',
    origin: 'Port of Spain Ferry Terminal',
    destination: 'Scarborough, Tobago',
    status: 'normal',
    delay_mins: 0,
    status_note: null,
    last_updated: new Date(Date.now() - 60 * 60000).toISOString(),
  },
  {
    id: 'route-007',
    code: 'PTSC-SNG',
    name: 'Sangre Grande Route',
    type: 'ptsc',
    origin: 'City Gate, Port of Spain',
    destination: 'Sangre Grande',
    status: 'normal',
    delay_mins: 0,
    status_note: null,
    last_updated: new Date(Date.now() - 45 * 60000).toISOString(),
  },
];

export const MOCK_SUMMARY: AreaSummary = {
  district: { code: 'POS', name: 'Port of Spain', region: 'North' },
  alerts: MOCK_ALERTS.filter((a) => a.district_code === 'POS' || a.severity === 'critical'),
  reports: MOCK_REPORTS.filter((r) => r.district_code === 'POS'),
  transport_disruptions: MOCK_TRANSPORT.filter((t) => t.status !== 'normal'),
  generated_at: new Date().toISOString(),
};
